repo_id:
  - 'meta-llama/Llama-2-7b-chat-hf'
local_model_hub: '/home/wangyishuo/llm-models/'
warm_up: 3
num_trials: 3
num_beams: 1 # default to greedy search
low_bit: "sym_int4"
in_out_pairs:
 # - '32-32'
  - '1024-128'
test_api:
  - "transformer_int4_gpu"
  # - "run_transformer_int4_stream2"
  # - "run_transformer_int4_stream"
  # - "ipex_fp16_gpu" # on Intel GPU
  # - "transformer_int4_gpu"  # on Intel GPU
  # - "optimize_model_gpu"  # on Intel GPU
  # - "deepspeed_transformer_int4_cpu" # on Intel SPR Server

